### ISSUE TITLE
Formula sha1 is disabled

### ISSUE THREAD

**Issue by ganeshramc** [renard/homebrew-cw#1]
When trying to install the packages this is the problem I'm facing. 
![image](https://user-images.githubusercontent.com/15274817/32717480-a2ff096c-c80e-11e7-9976-24aeeeb1c311.png)

**Comment by renard** [comment]
That is correct. I am facing a dilemma here. I don't know if I still maintain the python packages since `pip` seems to be the correct way to handle python packages
